// index.js

import { storiesOf } from '@storybook/vue';
import { withInfo } from 'storybook-addon-vue-info'

import MyButton from './Button.vue';


storiesOf('MyButton', module) // 상위 카테고리 지정
.addDecorator(withInfo)
  .add('뭐여 왜 안돼!', () => ({ 
    components: {  },
    template: '<b-button>roundexxxxxd</b-button>'
  }),
  {
    info: {
      summary: `
        You can set description for each props explicitly.
        \`\`\`js
        () => ({
          components: { BaseButton },
          template: '<base-button label="I\'m a button!"/>',
          description: {
            BaseButton: {
              props: {
                disabled: 'DISABLED!',
                type: 'TYPE!',
                label: 'LABEL!'
              },
              events: {
                click: 'AWESOME CLICK EVENT!'
              },
              slots: {
                default: 'DEFAULT SLOT, THAT\'S ALL!'
              }
            }
          }
        })
        \`\`\`
        This will override descriptions generated by docgen.
        ---
        **CAUTION!**
        If you write descriptions for events and slots without using vue-docgen-api,
        the addon shows the description no matter whether the slot or event exists.
        The reason is we cannot know what events and slots a component have:
        so the addon shows attributes user wrote as "information acquired in runtime".
      `
    }
  });


  